# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NKPbVfAan6UWBFZcfm5VP8PrBmj4tPw
"""

import pandas as pd
df=pd.DataFrame({'Ism':['Bibifotima','Hurixon','Mushtariybonu','Moxichehra','Madinaxon','Shuhratjon','Merojiddin','Nurmuhammad','Oybek','Muhammadaziz'],
                 'Familiya':["Jo'raboyeva","Jo'raboyeva",'Qadamova','Yusupaliyeva','Amakixonova','Shamshiddinov','Baxtiyorjonov','Jumanazarov','Akramov',"Ro'zaliyev"],
                 'Yoshi':['19','19','21','20','19','19','19','19','19','19'],
                 'Kursi':['2','2','2','2','2','2','2','2','2','2']
                 })
print(df)

df.to_excel('Bibifotima.xlsx',index=False,sheet_name='Sheetl')